version: 2

jobs:

  step_a:
    working_directory: ~/project
    docker:
      - image: python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "constraints.txt" }}-{{ checksum "setup.py" }}
      - run: pip install tox
      - run: tox --notest
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "constraints.txt" }}-{{ checksum "setup.py" }}
          paths:
            - ~/.cache/pip
            - .tox
      - run: tox
      - persist_to_workspace:
          root: .
          paths: .

  step_b:
    working_directory: ~/project
    docker:
      - image: python:3.5
    steps:
      - run: pwd && ls .
      - attach_workspace:
          at: ~/project
      - run: pwd && ls .
      - run: ls .tox

  step_c:
    working_directory: ~/project
    docker:
      - image: node:8
    steps:
      - attach_workspace:
          at: ~/project
      - run: node -e 'console.log(1)'

  step_db:
    docker:
      - image: python:3.6
        environment:
          PG_HOST: localhost
          PG_USER: ubuntu
      - image: postgres:9.5
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: db_name
          POSTGRES_PASSWORD: ""
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_HOST: "%"
          MYSQL_DATABASE: db_name
    steps:
      - run: apt-get update -qq && apt-get install -y build-essential postgresql libpq-dev mysql-client
      - run: pip install pymysql
      - run: mysql -u root -h 127.0.0.1 -P 3306 db_name -e 'show databases'
      - run: psql -U ubuntu -h localhost -p 5432 db_name -c '\l'

#  deploy:
#    docker:
#      - image: python:3.4
#    steps:
#      - run: mkdir -p ~/.ssh && ssh-keyscan -H xxx.xxx.xxx.xxx > ~/.ssh/known_hosts
#      - run: ssh ubuntu@xxx.xxx.xxx.xxx echo 1

workflows:
  version: 2
  flow:
    jobs:
      - step_a
      - step_b:
          requires:
            - step_a
      - step_c
      - step_db
#      - deploy:
#          requires:
#            - step_a
#            - step_b
#            - step_c
